# a=input("Enter your name:")
# print("Your name is " ,a)

x=input("Enter the first number::")
y=input("Enter the second number::")
print(x+y)
print(int (x)+int (y))
print("The value of ",x,"+",y,"is",int(x)+int(y))
print("The value of ",x,"-",y,"is",int(x)-int(y))
print("The value of ",x,"*",y,"is",int(x)*int(y))
print("The value of ",x,"/",y,"is",int(x)/int(y))
print("The value of ",x,"%",y,"is",int(x)%int(y))
print("The value of ",x,"//",y,"is",int(x)//int(y))